---
- hosts: all

  become: yes

  vars_prompt:
  - name: UserName
    prompt: "Enter Username"
    default: "hex-lab1"
    private: no

  - name: User_Password
    prompt: "Enter Pass"
    default: "hex-lab1"
    private: yes
    encrypt: "sha512_crypt"
    confirm: yes
    salt_size: 7

  tasks:

  - name: Add Several Users
    user: name="{{ UserName }}" comment="{{ UserName }}" password="{{ User_Password }}"
